inference:
    region: us-east-1
    role:
    deployment_configs:
        ComponentName: mlops-iot-regressor
        PlatformOS: LINUX
        PlatformArchitecture: X86_64
    lambdas:
        get-last-approved-model:
        create-packaging-job:
        check-packaging-job:
    s3_bucket_name: isengard-bpistone-mlops-iot-dev
training:
    region: us-east-1
    account_id:
    role:
    kms_alias: ml-kms-dev
    lambdas:
        create-compilation-job:
        check-compilation-job:
    platform_arch: X86_64
    platform_os: LINUX
    processing_ecr_image_name: mlops-iot-processing
    processing_ecr_image_tag: latest
    sagemaker_framework_version: 2.2
    sagemaker_python_version: py37
    s3_bucket_name:
    s3_processing_input_files_path: input/data
    s3_processing_output_files_path: output/data
    s3_training_artifact_path: artifact/training
    s3_training_artifact_name: sourcedir_dnn.tar.gz
    s3_training_input_files_path: output/data
    s3_training_output_files_path: output/model